repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

  - repo: local
    hooks:
      - id: cargo-check
        name: cargo-check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-clippy
        name: cargo-clippy
        entry: cargo clippy --all-targets --all-features
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-fmt
        name: cargo-fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false

      - id: cargo-test
        name: cargo-test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
